name: Traefik
version: 4.2.4
slug: traefik
description: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying
  microservices easy.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
init: false
stage: stable
boot: auto
ports:
  80/tcp: 80
  443/tcp: 443
  53/tcp: 53
  53/udp: 53
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  53/tcp: TCP
  53/udp: UDP
ingress: true
ingress_entry: dashboard/
hassio_role: default
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - config
  - share
  - ssl:rw
options:
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  dynamic_configuration_path: "/config/traefik/"
  http_port: 80
  https_port: 443
  tcp_port: 53
  udp_port: 53
  letsencrypt:
    enabled: false
    resolvers: []
  env_vars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  dynamic_configuration_path: str
  http_port: int?
  https_port: int?
  tcp_port: int?
  udp_port: int?
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  env_vars:
    - str
